/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2tbd2;

import com.formdev.flatlaf.FlatLightLaf;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.UIManager;

/**
 *
 * @author serli
 */
public class Main extends javax.swing.JFrame {

    private String mariaDBUrl = "jdbc:mariadb://mariadb-database.cgwlqlsfjpds.us-east-1.rds.amazonaws.com:3306/Proyecto_Teoria2";
    private String mariaDBUser = "admin";
    private String mariaDBPassword = "DanielySerlio";

    private String sqlServerUser = "danielserlio";
    private String sqlServerPassword = "danielserlio";
    private String sqlServerUrl = "jdbc:sqlserver://dbproyecto2.cqb9pqutso6u.us-east-1.rds.amazonaws.com:1433;databaseName=dbproyecto2;user=" + sqlServerUser + ";password=" + sqlServerPassword + ";encrypt=true;trustServerCertificate=true;loginTimeout=30;";

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTabbedPane = new javax.swing.JTabbedPane();
        tabConfiguracion = new javax.swing.JPanel();
        config_headerLabel = new javax.swing.JLabel();
        origenLabel = new javax.swing.JLabel();
        instanciaLabel = new javax.swing.JLabel();
        instanciaOrigen_tf = new javax.swing.JTextField();
        bddLabel = new javax.swing.JLabel();
        bddOrigen_tf = new javax.swing.JTextField();
        puertoLabel = new javax.swing.JLabel();
        puertoOrigen_tf = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        usernameOrigen_tf = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        probar_OrigenButton = new javax.swing.JButton();
        destinoLabel = new javax.swing.JLabel();
        instanciaLabel1 = new javax.swing.JLabel();
        instanciaDestino_tf = new javax.swing.JTextField();
        bddLabel1 = new javax.swing.JLabel();
        bddDestino_tf = new javax.swing.JTextField();
        puertoLabel1 = new javax.swing.JLabel();
        puertoDestino_tf = new javax.swing.JTextField();
        usernameLabel1 = new javax.swing.JLabel();
        usernameDestino_tf = new javax.swing.JTextField();
        passwordLabel1 = new javax.swing.JLabel();
        guardarButton = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        probar_DestinoButton = new javax.swing.JButton();
        tabTablas = new javax.swing.JPanel();
        tablas_headerLabel = new javax.swing.JLabel();
        sinReplicarLabel = new javax.swing.JLabel();
        replicandoLabel = new javax.swing.JLabel();
        toReplicando_button = new javax.swing.JButton();
        guardarTablas_button = new javax.swing.JButton();
        cancelarTablas_button = new javax.swing.JButton();
        MariaDB_scrollpane = new javax.swing.JScrollPane();
        SQLServer_list = new javax.swing.JList<>();
        SQLServer_scrollpane = new javax.swing.JScrollPane();
        MariaDB_list = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainTabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mainTabbedPaneStateChanged(evt);
            }
        });

        config_headerLabel.setText("Configuración de Bases de Datos");

        origenLabel.setText("Base de Datos de MariaDB");

        instanciaLabel.setText("Nombre Instancia");

        instanciaOrigen_tf.setText("MariaDB");
        instanciaOrigen_tf.setToolTipText("");

        bddLabel.setText("Nombre Base Datos");

        bddOrigen_tf.setText("Proyecto_Teoria2");

        puertoLabel.setText("Puerto");

        puertoOrigen_tf.setText("3306");

        usernameLabel.setText("Nombre Usuario");

        usernameOrigen_tf.setText("admin");

        passwordLabel.setText("Password");

        probar_OrigenButton.setText("Probar");
        probar_OrigenButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                probar_OrigenButtonMouseClicked(evt);
            }
        });

        destinoLabel.setText("Base de Datos SQL Server");

        instanciaLabel1.setText("Nombre Instancia");

        instanciaDestino_tf.setText("SQLServer");

        bddLabel1.setText("Nombre Base Datos");

        bddDestino_tf.setText("dbproyecto2");
        bddDestino_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bddDestino_tfActionPerformed(evt);
            }
        });

        puertoLabel1.setText("Puerto");

        puertoDestino_tf.setText("1433");

        usernameLabel1.setText("Nombre Usuario");

        usernameDestino_tf.setText("danielserlio");

        passwordLabel1.setText("Password");

        guardarButton.setText("Guardar");

        jPasswordField1.setText("DanielySerlio");

        jPasswordField2.setText("danielserlio");

        probar_DestinoButton.setText("Probar");
        probar_DestinoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                probar_DestinoButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tabConfiguracionLayout = new javax.swing.GroupLayout(tabConfiguracion);
        tabConfiguracion.setLayout(tabConfiguracionLayout);
        tabConfiguracionLayout.setHorizontalGroup(
            tabConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabConfiguracionLayout.createSequentialGroup()
                .addGroup(tabConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabConfiguracionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(tabConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(origenLabel)
                            .addGroup(tabConfiguracionLayout.createSequentialGroup()
                                .addComponent(instanciaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(instanciaOrigen_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tabConfiguracionLayout.createSequentialGroup()
                                .addComponent(bddLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bddOrigen_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tabConfiguracionLayout.createSequentialGroup()
                                .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPasswordField1))
                            .addGroup(tabConfiguracionLayout.createSequentialGroup()
                                .addGroup(tabConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(puertoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(tabConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(puertoOrigen_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usernameOrigen_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addGroup(tabConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(destinoLabel)
                            .addGroup(tabConfiguracionLayout.createSequentialGroup()
                                .addComponent(instanciaLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(instanciaDestino_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tabConfiguracionLayout.createSequentialGroup()
                                .addComponent(bddLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bddDestino_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tabConfiguracionLayout.createSequentialGroup()
                                .addComponent(passwordLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPasswordField2))
                            .addGroup(tabConfiguracionLayout.createSequentialGroup()
                                .addGroup(tabConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(puertoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usernameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(tabConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(puertoDestino_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usernameDestino_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(tabConfiguracionLayout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(config_headerLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabConfiguracionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(guardarButton))
            .addGroup(tabConfiguracionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(probar_OrigenButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(probar_DestinoButton)
                .addGap(217, 217, 217))
        );
        tabConfiguracionLayout.setVerticalGroup(
            tabConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabConfiguracionLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(config_headerLabel)
                .addGap(18, 18, 18)
                .addGroup(tabConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabConfiguracionLayout.createSequentialGroup()
                        .addComponent(origenLabel)
                        .addGap(18, 18, 18)
                        .addGroup(tabConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(instanciaLabel)
                            .addComponent(instanciaOrigen_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tabConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bddLabel)
                            .addComponent(bddOrigen_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tabConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(puertoLabel)
                            .addComponent(puertoOrigen_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tabConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernameLabel)
                            .addComponent(usernameOrigen_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(tabConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordLabel)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tabConfiguracionLayout.createSequentialGroup()
                        .addComponent(destinoLabel)
                        .addGap(18, 18, 18)
                        .addGroup(tabConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(instanciaLabel1)
                            .addComponent(instanciaDestino_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tabConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bddLabel1)
                            .addComponent(bddDestino_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tabConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(puertoLabel1)
                            .addComponent(puertoDestino_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tabConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernameLabel1)
                            .addComponent(usernameDestino_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(tabConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordLabel1)
                            .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(tabConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(probar_OrigenButton)
                    .addComponent(probar_DestinoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(guardarButton)
                .addContainerGap())
        );

        mainTabbedPane.addTab("Configuración", tabConfiguracion);

        tablas_headerLabel.setText("Tablas BD Origen");

        sinReplicarLabel.setText("MariaDB");

        replicandoLabel.setText("SQL Server");

        toReplicando_button.setText(">>");
        toReplicando_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toReplicando_buttonMouseClicked(evt);
            }
        });
        toReplicando_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toReplicando_buttonActionPerformed(evt);
            }
        });

        guardarTablas_button.setText("Guardar");

        cancelarTablas_button.setText("Cancelar");

        MariaDB_scrollpane.setViewportView(SQLServer_list);

        SQLServer_scrollpane.setViewportView(MariaDB_list);

        javax.swing.GroupLayout tabTablasLayout = new javax.swing.GroupLayout(tabTablas);
        tabTablas.setLayout(tabTablasLayout);
        tabTablasLayout.setHorizontalGroup(
            tabTablasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabTablasLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(sinReplicarLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(replicandoLabel)
                .addGap(117, 117, 117))
            .addGroup(tabTablasLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(SQLServer_scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(tabTablasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(guardarTablas_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toReplicando_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelarTablas_button, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(MariaDB_scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(tabTablasLayout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(tablas_headerLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabTablasLayout.setVerticalGroup(
            tabTablasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabTablasLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(tablas_headerLabel)
                .addGap(18, 18, 18)
                .addGroup(tabTablasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sinReplicarLabel)
                    .addComponent(replicandoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabTablasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MariaDB_scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SQLServer_scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tabTablasLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(toReplicando_button)
                        .addGap(53, 53, 53)
                        .addComponent(guardarTablas_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelarTablas_button)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Tablas", tabTablas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void probar_DestinoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_probar_DestinoButtonMouseClicked
        Conexion_SQLServer prueba = new Conexion_SQLServer();
        prueba.connect();
        System.out.println("done");
    }//GEN-LAST:event_probar_DestinoButtonMouseClicked

    private void probar_OrigenButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_probar_OrigenButtonMouseClicked
        Conexion_MariaDB prueba = new Conexion_MariaDB();
        prueba.Conexion_MariaDB();
        System.out.println("done maria");
    }//GEN-LAST:event_probar_OrigenButtonMouseClicked

    private void bddDestino_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bddDestino_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bddDestino_tfActionPerformed

    private void mainTabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mainTabbedPaneStateChanged

        //Actualizar JList de TABLES de MariaDB
        DefaultListModel<String> MariaListModel = new DefaultListModel<>();
        try {
            Connection connection = DriverManager.getConnection(mariaDBUrl, mariaDBUser, mariaDBPassword);
            String sql = "SHOW TABLES FROM Proyecto_Teoria2";
            // Create a statement
            Statement statement = connection.createStatement();
            // Execute the query
            ResultSet resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {
                String tableName = resultSet.getString(1);
                MariaListModel.addElement(tableName);
            }
            MariaDB_list.setModel(MariaListModel);
            resultSet.close();
            connection.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }

        //Actualizar JList de TABLES de SQL Server
        DefaultListModel<String> ServerListModel = new DefaultListModel<>();
        try {
            Connection connection = DriverManager.getConnection(sqlServerUrl);
            String sql = "SELECT TABLE_NAME\n"
                    + "FROM INFORMATION_SCHEMA.TABLES\n"
                    + "WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_CATALOG = 'dbproyecto2';";
            // Create a statement
            Statement statement = connection.createStatement();
            // Execute the query
            ResultSet resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {
                String tableName = resultSet.getString(1);
                ServerListModel.addElement(tableName);
            }
            SQLServer_list.setModel(ServerListModel);
            resultSet.close();
            connection.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_mainTabbedPaneStateChanged

    private void toReplicando_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toReplicando_buttonMouseClicked
        MariaDBToSQLServerExporter exportar = new MariaDBToSQLServerExporter();
        exportar.exportMariaDBToSQLServer(MariaDB_list);
    }//GEN-LAST:event_toReplicando_buttonMouseClicked

    private void toReplicando_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toReplicando_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toReplicando_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception e) {
            System.out.println("failed to initialized");
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> MariaDB_list;
    private javax.swing.JScrollPane MariaDB_scrollpane;
    private javax.swing.JList<String> SQLServer_list;
    private javax.swing.JScrollPane SQLServer_scrollpane;
    private javax.swing.JTextField bddDestino_tf;
    private javax.swing.JLabel bddLabel;
    private javax.swing.JLabel bddLabel1;
    private javax.swing.JTextField bddOrigen_tf;
    private javax.swing.JButton cancelarTablas_button;
    private javax.swing.JLabel config_headerLabel;
    private javax.swing.JLabel destinoLabel;
    private javax.swing.JButton guardarButton;
    private javax.swing.JButton guardarTablas_button;
    private javax.swing.JTextField instanciaDestino_tf;
    private javax.swing.JLabel instanciaLabel;
    private javax.swing.JLabel instanciaLabel1;
    private javax.swing.JTextField instanciaOrigen_tf;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JLabel origenLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel passwordLabel1;
    private javax.swing.JButton probar_DestinoButton;
    private javax.swing.JButton probar_OrigenButton;
    private javax.swing.JTextField puertoDestino_tf;
    private javax.swing.JLabel puertoLabel;
    private javax.swing.JLabel puertoLabel1;
    private javax.swing.JTextField puertoOrigen_tf;
    private javax.swing.JLabel replicandoLabel;
    private javax.swing.JLabel sinReplicarLabel;
    private javax.swing.JPanel tabConfiguracion;
    private javax.swing.JPanel tabTablas;
    private javax.swing.JLabel tablas_headerLabel;
    private javax.swing.JButton toReplicando_button;
    private javax.swing.JTextField usernameDestino_tf;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel usernameLabel1;
    private javax.swing.JTextField usernameOrigen_tf;
    // End of variables declaration//GEN-END:variables
}
